import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicons/favicon-32x32-lexi-logo-icon.png" sizes="32x32" />
        <link rel="icon" href="/favicons/favicon-16x16-lexi-logo-icon.png" sizes="16x16" />
        <link rel="apple-touch-icon" href="/favicons/apple-touch-icon-180x180-lexi-logo-icon.png" />
        <link rel="manifest" href="/favicons/manifest.json" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
